### ISSUE TITLE
Instantiate DatePickerDialog from Fragment

### ISSUE THREAD

**Issue by larrytech7** [borax12/MaterialDateRangePicker#47] opened 2016-08-24 14:05 UTC
Am using the v4 support version of the android Fragment and am unable to instate the date picker with version 1.7 of the library. All attempts to set the listener and the fragmentManager fail. The parameters are not being accepted. The listener is implemented on the Fragment and the fragment is hosted in an activity that extends AppCompatActivity.

**Comment by Kamil-Kaminski** [comment] 2016-08-24 14:13
I had the same issue today - to show DatePickerDialog inside v4 support Fragment, you have to do something like that:
`dialog.show(getActivity().getFragmentManager(), "tag");`

**Comment by larrytech7** [comment] 2016-08-24 14:15
Ok works for the show method. What about the instantiate method? What needs to go there in this case?

**Comment by Kamil-Kaminski** [comment] 2016-08-24 14:17
Hmm, for instantiating the dialog, I do something like that:

```
       TimePickerDialog timePickerDialog = TimePickerDialog.newInstance(new TimePickerDialog.OnTimeSetListener() {

            @Override
            public void onTimeSet(RadialPickerLayout view, int hourOfDay, int minute, int hourOfDayEnd, int minuteEnd) {
 // my stuff
            }
        }, startHour, startMinute, true);
```

**Comment by larrytech7** [comment] 2016-08-24 14:19
Ohh, i see but that's not really how want to use it. I have implemented the interface on my fragment so i was expecting to just put this in the place.

```
DatePickerDialog dpd = DatePickerDialog
                .newInstance(
                this,
                now.get(Calendar.YEAR),
                now.get(Calendar.MONTH),
                now.get(Calendar.DAY_OF_MONTH)
                );

@But this doesn't seem to validate.
```

**Comment by larrytech7** [comment] 2016-08-27 20:57
Anyone with Fix, this thing is retarding my project. Need some assistance with this or i may switch to move forward.

**Comment by heysupratim** [comment] 2016-10-16 14:51
@larrytech7 the instance method is just dependent on the reference to DatePickerDialog.OnDateSetListener , so it can be a fragment or an activity

**Comment by heysupratim** [comment] 2016-10-16 15:53
@csbenz - can you check the reproducibility of this issue ?

**Comment by a7medpa** [comment] 2017-03-20 21:10
This simply does not work with fragments! Please post any working sample up if it is actually working with fragments, from what I see it does not work and everyone seems to have an issue with it.

**Comment by Zenger** [comment] 2017-11-25 00:49
I know this is old but if somebody comes back here and is using this in a Kotlin project the @Kaminiak is right in your .show method don't use `fragmentManager` but use `activity.fragmentManager` and things will go smooth!

**Comment by bliveinhack** [comment] 2018-02-23 08:28
@borax12 @Zenger 
we can not use `activity.fragmentmanager` inside the `fragment`. we must have to use `fragment's childFragmentmanager` according to android official 

> You can now embed fragments inside fragments. This is useful for a variety of situations in which you want to place dynamic and re-usable UI components into a UI component that is itself dynamic and re-usable. For example, if you use ViewPager to create fragments that swipe left and right and consume a majority of the screen space, you can now insert fragments into each fragment page.

> To nest a fragment, simply call getChildFragmentManager() on the Fragment in which you want to add a fragment. This returns a FragmentManager that you can use like you normally do from the top-level activity to create fragment transactions. For example, here’s some code that adds a fragment from within an existing Fragment class:

it would be great if you can just fix for support fragment manager.

Regards.

**Comment by dutchmo** [comment] 2018-04-25 12:14
I'm sure this is because the parent library doesn't use support fragments:
https://github.com/wdullaer/MaterialDateTimePicker#why-not-use-supportdialogfragment

Their argument probably doesn't hold up since google has now deprecated fragments in favor of support fragments, but yeah. It would be an issue for the parent library to change that.

**Comment by heysupratim** [comment] 2019-08-03 19:46
This is fixed in the upcoming release. Uses 4.2.1 wduller codebase which uses support fragments

**Closed as completed by heysupratim** 2019-08-03 19:46 UTC
