### ISSUE TITLE
I use the method setAccentColor but the color not changed

### ISSUE THREAD

**Issue by AngelusCuba** [borax12/MaterialDateRangePicker#78] opened 2017-11-15 16:55 UTC
Here is my code

```
Calendar now = Calendar.getInstance();
                DatePickerDialog dpd = DatePickerDialog.newInstance(
                        index.this,
                        now.get(Calendar.YEAR),
                        now.get(Calendar.MONTH),
                        now.get(Calendar.DAY_OF_MONTH)
                );

                dpd.setAccentColor(R.color.colorprincipal);
                Toast toast1 =
                        Toast.makeText(getApplicationContext(),
                                dpd.getAccentColor(), Toast.LENGTH_LONG);

                toast1.show();
                dpd.show(getFragmentManager(), "fechainicio");
```

I write a toast that shows the accent color
![spectacle tj6343](https://user-images.githubusercontent.com/21693591/32848813-56511ea2-ca25-11e7-9229-ac9919d95d3e.png)

**Comment by RamithRD** [comment] 2018-07-10 05:34
Try setting the color programmatically , example:

dpd.setAccentColor(Color.parseColor("#ffa800"));

Worked on my end.

**Comment by iAmVishal16** [comment] 2019-05-03 10:44
> Here is my code
> 
> ```
> Calendar now = Calendar.getInstance();
>                 DatePickerDialog dpd = DatePickerDialog.newInstance(
>                         index.this,
>                         now.get(Calendar.YEAR),
>                         now.get(Calendar.MONTH),
>                         now.get(Calendar.DAY_OF_MONTH)
>                 );
> 
>                 dpd.setAccentColor(R.color.colorprincipal);
>                 Toast toast1 =
>                         Toast.makeText(getApplicationContext(),
>                                 dpd.getAccentColor(), Toast.LENGTH_LONG);
> 
>                 toast1.show();
>                 dpd.show(getFragmentManager(), "fechainicio");
> ```
> 
> I write a toast that shows the accent color
> ![spectacle tj6343](https://user-images.githubusercontent.com/21693591/32848813-56511ea2-ca25-11e7-9229-ac9919d95d3e.png)

  Got the same issue occurs?

**Comment by heysupratim** [comment] 2019-08-03 20:18
Not able to reproduce this issue. Closing it

**Closed as completed by heysupratim** 2019-08-03 20:18 UTC
